{
    "author":"test",
    "version":"1.0",
    "module":"user",
    "title":"用户模块",
    "cover":"cover.png",
    "describe":"这是一个用户管理模块的demo",
    "list":{
        "name":"User",
        "icon":"icon-user-follow",
        "menu":{
            "0":{
                "name":"用户管理",
                "url":"app.user",
                "permissions":{
                    "r":4,
                    "w":2,
                    "x":1
                }
            },
            "1":{
                "name":"添加用户",
                "url":"user_management",
                "permissions":{
                    "r":4,
                    "w":2,
                    "x":1
                }
            },
            "2":{
                "name":"数据统计",
                "url":"user_management",
                "permissions":{
                    "r":4,
                    "w":2,
                    "x":1
                    }
            }
        }
    },
    "apis":{

    }
}